name: Test Download Artifact S3 Action
on:
  push:
  pull_request:
    paths:
      - '.github/actions/download-artifact-s3/**'
      - '!**/*.md'

jobs:

  build:
    name: test-download-artifact-s3-build

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
      max-parallel: 1

    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: npm install
      run: npm install

    - name: Compile
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Format
      run: npm run format-check

    # Test end-to-end by uploading two artifacts and then downloading them
    - name: Create artifacts
      run: |
        mkdir -p path/to/artifact-A
        mkdir -p path/to/artifact-B
        echo "Lorem ipsum dolor sit amet" > path/to/artifact-A/file-A.txt
        echo "Hello world from file B" > path/to/artifact-B/file-B.txt
        ls -lR path

    - name: Upload artifact A
      uses: actions/upload-artifact@v4
      with:
        name: Artifact-A-${{ matrix.runs-on }}
        path: ${{ github.workspace }}/path/to/artifact-A

    - name: Upload artifact B
      uses: actions/upload-artifact@v4
      with:
        name: Artifact-B-${{ matrix.runs-on }}
        path: LICENSE

    # Test downloading a single artifact
    - name: Download artifact A
      uses: actions/download-artifact@v4
      with:
        name: 'Artifact-A-${{ matrix.runs-on }}'
        path: some/new/path

    # Test downloading an artifact using tilde expansion
    - name: Download artifact A
      uses: actions/download-artifact@v4
      with:
        name: 'Artifact-A-${{ matrix.runs-on }}'
        path: ~/some/path/with/a/tilde

    - name: Verify successful download
      run: |
        $file1 = "${{ github.workspace }}/some/new/path/LICENSE"
        $file2 = "~/some/path/with/a/tilde/LICENSE"
        if(!(Test-Path -path $file1) -or !(Test-Path -path $file2))
        {
            Write-Error "Expected files do not exist"
        }
        if(!((Get-Content $file1) -ceq "BSD License") -or !((Get-Content $file2) -ceq "BSD License"))
        {
            Write-Error "File contents of downloaded artifacts are incorrect"
        }
      shell: pwsh

    # Test downloading both artifacts at once
    - name: Download all Artifacts
      uses: actions/download-artifact@v4
      with:
        path: some/other/path

    - name: Verify successful download
      run: |
        $fileA = "${{ github.workspace }}/some/other/path/Artifact-A-${{ matrix.runs-on }}/LICENSE"
        $fileB = "${{ github.workspace }}/some/other/path/Artifact-B-${{ matrix.runs-on }}/LICENSE"
        if(!(Test-Path -path $fileA) -or !(Test-Path -path $fileB))
        {
            Write-Error "Expected files do not exist"
        }
        if(!((Get-Content $fileA) -ceq "BSD License") -or !((Get-Content $fileB) -ceq "BSD License"))
        {
            Write-Error "File contents of downloaded artifacts are incorrect"
        }
      shell: pwsh
